---
title: "Sleepless in New England: The Unseen Cost of Greatness"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 

An analysis of the price New Englanders pay to support their sports dynasties. 

The big 4 sports teams of New England - the Bruins (NHL), Celtics (NBA), Patriots (NFL), and Red Sox (MLB) - have enjoyed an unprecedented run of success, beginning in 2001 with the Patriots' win in Super Bowl XXXVI and continuing through the present, with the Red Sox once again reaching the World Series this year. 

Including that Patriots 2001 championship, Boston teams have appeared in a title game an astonishing 16 times.

As these teams rose to prominence, they captured the interest of the nation - or at least of the national broadcasters. As a result, a disproportionate number of their games have been scheduled in the late-evening, "prime time" slot. 

And with games stretching longer and longer - especially in the MLB and NFL - diehard Boston fans have seen their bedtimes pushed back later and later.

Exactly to what extent has this phenomenon impacted the sleep & productivity of working & learning Bostonians, and what other sports-centric cities (if any) have faced similar burdens?